import Head from 'next/head'
import Image from 'next/image'

import News from '../components/News';
import Tabs from '../components/Tabs';
import Features from '../components/Features';

import styles from '../styles/home.module.scss'

export default function Home() {
  return (
    <>
      <Head>
        <title>GenShin | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={`${styles.hero} relative flex justify-center items-end h-screen`}>
        <div className='hidden absolute top-8 sm:block'>
          <Image
            src="/images/logo/logo.png"
            alt="Logo"
            width={194}
            height={70}
          />
        </div>
        <div className='absolute top-52 left-40 w-96 text-white lg:top-60 lg:left-28 sm:top-80 sm:left-8 sm:w-64'>
          <h1 className='text-4xl font-semibold text-orange-200 md:text-2xl'>An Open-World</h1>
          <h1 className='text-4xl font-semibold md:text-2xl'>Action RPG Game</h1>
          <p className='text-md leading-tight opacity-70 mt-3 md:text-sm'>In the world of Teyvat — where all kinds of elemental powers constantly surge — epic adventures await, fearless travelers!</p>
        </div>
        <div className='grid grid-cols-4 gap-8 mx-10 mb-24 md:grid-cols-2 md:mb-12 sm:hidden'>
          <a href="" className={`${styles.download} flex justify-center items-center rounded-lg p-4`}>
            <Image
              src="/images/logo/Playstation.png"
              alt='PlayStation'
              width={160}
              height={18}
            />
          </a>
          <a href="" className={`${styles.download} flex justify-center items-center rounded-lg p-4`}>
            <Image
              src="/images/logo/AppStore.png"
              alt='PlayStation'
              width={160}
              height={38}
            />
          </a>
          <a href="" className={`${styles.download} flex justify-center items-center rounded-lg p-4`}>
            <Image
              src="/images/logo/GooglePlay.png"
              alt='PlayStation'
              width={160}
              height={38}
            />
          </a>
          <a href="" className={`${styles.download} flex justify-center items-center rounded-lg p-4`}>
            <Image
              src="/images/logo/Windows.png"
              alt='PlayStation'
              width={160}
              height={32}
            />
          </a>
        </div>
      </section>

      <section id="news" className={`${styles.news} flex flex-col items-center justify-center h-screen lg:h-auto`}>
        <h1 className='text-4xl font-bold text-orange-100 mb-16 lg:mt-20 sm:mt-16 sm:mb-12'>— News —</h1>
        <div className='flex w-4/5 mb-20 xl:w-11/12 lg:flex-col lg:items-center lg:w-2/3 md:w-4/5 sm:mb-16'>
          <div className='w-1/2 lg:w-full'>
            <News />
          </div>
          <div className={`${styles.newstabs} w-1/2 lg:w-full lg:pb-2`}>
            <Tabs />
          </div>
        </div>
      </section>

      <section className={`${styles.features} flex flex-col items-center h-screen bg-blend-overlay xl:h-auto`}>
        <h1 className='text-4xl font-bold text-orange-700 mt-20 mb-12 lg:mt-16 sm:mt-12 sm:mb-8 sm:text-2xl'>— Game Features —</h1>
        <div className='w-2/3 xl:mb-16 sm:w-4/5 sm:mb-24'>
          <Features />
        </div>
      </section>
    </>
  )
}
