import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/home.module.scss'

export default function Home() {
  return (
    <>
      <Head>
        <title>GenShin | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.hero}>
        
      </section>
    </>
  )
}
